### ISSUE TITLE
Issue in script 2.0 - fetching elevation raster failing

### ISSUE THREAD

**Issue by natesheehan** [Hussein-Mahfouz/cycle-networks#11]
Hey Hussein - I've spotted a small issue with regards to fetching raster elevation data for the chosen city.

So currently the `renv` is using this version of elevatr

```{json}
    "elevatr": {
      "Package": "elevatr",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "491cf636e7ee02fa541ee02734d1353b"
    },
```

When I used this version and ran script 2.0, I got this error:
``` {r}
Error in if ((is.null(sp::wkt(locations)) | nchar(sp::wkt(locations)) == : argument is of length zero
```
When running the following lines:
```{r}
# specify the crs
prj_elev <- "+init=EPSG:4326"
# download elevation for study area using elevatr
city_elev <- elevatr::get_elev_raster(city_geom, z= 9, prj = prj_elev, expand = 0.05)
```

This is a known issue in elevatr and is due to CRS changes made to the `raster` package. See https://github.com/jhollist/elevatr/issues/49

To run the script,  I have changed the `elevatr` version to the latest from CRAN and refactored the elevation call as:
```{r}
city_elev <- elevatr::get_elev_raster(city_geom, z= 9, expand = 0.05)
```
I believe, correct me if I am wrong, that you dont need to declare the `prj_elev` - as this is already detected as part of the get call.

**Comment by Hussein-Mahfouz** [comment]
Hi Nathanael, great to see you here! Thanks for this, I followed your suggestion and it should work smoothly now. Looks like you're right, no need to declare the projection either. I've updated the code + renv lockfile in commit d9d655fc2cb7e6d4f377b63525c3565dc7563aa5
