### ISSUE TITLE
MSOA file format, name, and location

### ISSUE THREAD

**Issue by ShipleyWill** [Hussein-Mahfouz/cycle-networks#8]
Hi Robin and Hussain,

First of all, thanks for a very interesting read and some excellent supporting resources! 

I'm trying to reproduce your method for my local district (Bradford), but I'm falling at the first hurdle. Very much a beginner.

Accessing MSOA file:
I navigate to: http://geoportal.statistics.gov.uk/datasets/826dc85fb600440889480f4d9dbb1a24_0
I click the 'download' tab and am presented with a number of file formats (CSV, KML, SHP, GeoJSON)
I download the .csv version (~200KB)
**Is this the correct file?** (I'm guessing not, as it's supposed to be 100MB, but there isn't one of that size.

Saving the MSOA file:
I add it to a new file I created in data-raw called "MSOA_2011_Boundaries"
**Am I supposed to create this new file?**

Naming the MSOA file:
I run:
`source("R/_1.0_get_flow_data.R")`
I get:
_Error: 'data-raw/MSOA_2011_to_Major_Towns_and_Cities.csv' does not exist in current working directory ('C:/Users/mnwjs/Documents/BfdCycles')._

This file name does not match the one in my folder or the ReadMe, so I change it from "Middle_Layer_Super_Output_Areas_(December_2011)_Boundaries.csv" to "MSOA_2011_to_Major_Towns_and_Cities.csv".
**Do the file names and locations in the ReadMe match those that the script reads from? Or is this something to do with me choosing the wrong WD?**

Format of the MSOA file:
I run again:
`source("R/_1.0_get_flow_data.R")`
I get:
_Error: Can't rename columns that don't exist.
x Column `TCITY15NM` doesn't exist._
**I notice the statistics.gov website says the files were uploaded 21/06/2021. Have they changed the names/formats since your paper? Or have I just got the wrong file? I know which one I think is more likely!**

As I said, total newbie, here! Please don't take my failure as a comment on your helpful notes, these issues are clearly down to my own ignorance. I'm using this project to learn about R, and to help with local campaigns, and because I find it fascinating. Any (idiot-proof) help gratefully received.

Will

**Comment by Hussein-Mahfouz** [comment]
Hi Will

Thanks for reaching out! Your feedback is helpful in pointing out things we are missing. 

1) The `MSOA_2011_to_Major_Towns_and_Cities.csv` file was missing from the repo. Sorry! I've just added it to the data-raw folder
2) The _Middle Layer Super Output Areas (December 2011) Boundaries_ should be downloaded as .shp and saved in `data-raw/MSOA_2011_Boundaries/[Add files here]`

Can you try again and let us know if works?

**Comment by ShipleyWill** [comment]
That's fab Hussein - script 1 complete.
