### ISSUE TITLE
Script 2 - Error in library(slopes) : there is no package called ‘slopes’, and other issues

### ISSUE THREAD

**Issue by ShipleyWill** [Hussein-Mahfouz/cycle-networks#9]
1) I have had to install several packages in R to get the scripts to run, even after using the build.r script. This has so far been no problem, but I cant find package 'slopes'.

There is a package 'SLOPE', so I tried editing script 2 in several places from 'slopes' to 'SLOPE', and continued. This solved the package error message.

2) The .shp files then could not be found, I think due to the file names including brackets, whereas the file names in the script have double underscores, e.g.

My file in MSOA_2011_Boundaries is 'Middle_Layer_Super_Output_Areas_(December_2011)_Boundaries'
But the script wants 'Middle_Layer_Super_Output_Areas__December_2011__Boundaries'

So I changed my file names to double underscores.

3) The script then seems to run, until I get this error:
Error in if ((is.null(sp::wkt(locations)) | nchar(sp::wkt(locations)) ==  : 
  argument is of length zero
In addition: Warning messages:
1: In sp::wkt(locations) : CRS object has no comment
2: In sp::wkt(locations) : CRS object has no comment
3: In sp::wkt(locations) : CRS object has no comment

And I have no idea what this means. I realise this might have been caused by my amateur modifications! What am I doing wrong?

**Comment by Hussein-Mahfouz** [comment]
1) Did you run:
```
install.packages("renv")
renv::restore()
```
before running the build.r script? That is meant to install all the packages for you (correct versions as well. 

2) The slopes package is here https://github.com/Hussein-Mahfouz/cycle-networks/tree/main/R

3) I would edit the file name of the files you downloaded by copy-pasting the name from the script. Don't forget to add all the files not just the shp (dbf, prj etc). If the error persists, try running script 2 line by line and let me know where the error is raised (which line).

**Comment by ShipleyWill** [comment]
1. I had run this code, but I don't think it got to the end. I've now installed RTools40 and re-run. Seems to be working this time!
2. File names edited, and I have all the associated files in my MSOA_2011_Boundaries folder.
3. Trying again - will let you know...

Thanks for all your help, Hussein.

**Comment by ShipleyWill** [comment]
No luck.

I tried to run again several times:

`install.packages("renv")
renv::restore()`

And it starts installing fine. But then I get:

Rcurl.h:4:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-41~1.0/etc/x64/Makeconf:238: base64.o] Error 1
ERROR: compilation failed for package 'RCurl'
* removing 'C:/Users/mnwjs/Documents/R/win-library/4.1/.renv/1/RCurl'
Error: install of package 'RCurl' failed [error code 1]

I've tried downloading RCurl separately from RStudio, and from CRAN, but when I re-run the command, it always fails at this point. I don't want to give up, but understand if you've got better things to do than help me...

**Comment by Robinlovelace** [comment]
Hi @ShipleyWill, it's worth persisting on this I think, should be doable. I think you can install all the dependencies without needing `renv::restore()`. What happens when you try

```r
install.packages("RCurl")
```

?

**Comment by Robinlovelace** [comment]
Also try installing the pesky slopes package as follows:

```
remotes::install_github("itsleeds/slopes")
```

**Comment by ShipleyWill** [comment]
> Hi @ShipleyWill, it's worth persisting on this I think, should be doable. I think you can install all the dependencies without needing `renv::restore()`. What happens when you try
> 
> ```r
> install.packages("RCurl")
> ```
> 
> ?

That works:
> install.packages("RCurl")
Installing package into ‘C:/Users/mnwjs/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
also installing the dependency ‘bitops’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/bitops_1.0-7.zip'
Content type 'application/zip' length 42470 bytes (41 KB)
downloaded 41 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/RCurl_1.98-1.3.zip'
Content type 'application/zip' length 3072176 bytes (2.9 MB)
downloaded 2.9 MB

package ‘bitops’ successfully unpacked and MD5 sums checked
package ‘RCurl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\mnwjs\AppData\Local\Temp\RtmpUJf8GZ\downloaded_packages

But then it still fails when I run renv::restore()

**Comment by ShipleyWill** [comment]
> Also try installing the pesky slopes package as follows:
> 
> ```
> remotes::install_github("itsleeds/slopes")
> ```

This give an error:

> remotes::install_github("itsleeds/slopes")
Error in loadNamespace(x) : there is no package called ‘remotes’

**Comment by ShipleyWill** [comment]
So I've installed 'remotes' seperately, and then

remotes::install_github("itsleeds/slopes")

Has worked!

**Comment by Hussein-Mahfouz** [comment]
I think what @Robinlovelace is suggesting is for you to run the scripts without `renv::restore()`
So you can go through the scripts sequentially and run them one by one (installing the missing packages as you go). You only need to run the numbered scripts.

This should mostly work. The reason we use `renv` is so that you can use the same version of the packages that were used when writing the script. Functions may behave differently / be depreciated as package versions are released....but maybe this won't be an issue

Could you try that and let us know how it goes?

**Comment by ShipleyWill** [comment]
Got it.

To be honest, that's what I was trying earlier on, but I was hesitant because:
1) I wasn't sure how far through a script I'd get, only to have to run it again after installing the relevant package, 
2) I want to do it "properly" because then I'll learn the most, and
3) I didn't want to mess it up and then plaster Twitter with something stupid/wrong (especially as it would be linked to you wonderful people).

I will press on with patience (solution to 1), take a course in R (solution to 2), and send you what comes out of the other end before sharing (solution to 3)!!

Thank you both so much.
